config/routes.rb
Rails.application.routes.draw do
  resources :localidades do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :iniciadores do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :objetos_mensuras
  resources :mensuras do
    member do
      get :reporte
    end
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :expedientes do
    collection do
         get :busqueda
         get :asignar
         post :resultado_busqueda
    end
  end
  resources :propiedades do
    collection do
      get :consulta
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
    member do
      get :mensuras
    end
  end
  resources :parcelas do
    collection do
      get :mensuraPar
      post :guardar_mensuras
    end
  end
  resources :visadores do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :jurisdicciones do
    member do
      get :get_mensure_attributes #  /jurisdicciones/:id/get_mensure_attributes
    end
  end
  resources :departamentos
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/barrio.rb
class Barrio < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
	has_many :localidad
	has_many :mensura
end

app/models/expediente.rb
class Expediente < ApplicationRecord
	belongs_to :tipo_expediente
	has_one :mensura

	def fecha_to_s
		fecha.strftime('%d-%m-%Y')
	end
end

app/models/iniciador.rb
class Iniciador < ApplicationRecord
	belongs_to :tipo_documento
	validates :tipo_documento_id, presence: true
	validates :matricula, presence: true
  validates :razon_social, presence: true
 end

app/models/jurisdiccion.rb
class Jurisdiccion < ApplicationRecord
  belongs_to :departamento
  has_many :mensura

  def caracter
  	LetraMensura.where(codigo: departamento_id).first.letra_mensura
  end

  def number
  	mensura = Mensura.where(mensura_letra: caracter).order(mensura_nro: :desc).first
  	if mensura
  	  mensura.mensura_nro
  	else
  	  0
  	end
  end
end

app/models/letra_mensura.rb
class LetraMensura < ApplicationRecord
  self.table_name = "letra_mensura"
end

app/models/localidad.rb
class Localidad < ApplicationRecord
	belongs_to :departamento
end

app/models/logs_accion.rb
class Logs_Accion < ApplicationRecord
end

app/models/manzana.rb
class Manzana < ApplicationRecord
end

app/models/mensura.rb
class Mensura < ApplicationRecord
	belongs_to :jurisdiccion
	belongs_to :expediente, foreign_key: :expte_id, optional: true
	belongs_to :rectificacion, foreign_key: :rectificacion_id, optional: true, class_name: 'Mensura'
	belongs_to :iniciador, optional: true
	belongs_to :localidad, optional: true
	belongs_to :visador, optional: true
	belongs_to :objetos_mensura, optional: true, foreign_key: :objeto_id
	belongs_to :departamento, optional: true
	belongs_to :parcela, optional: true
	validates :jurisdiccion_id, :objeto_id, :fecha_registracion, presence: true

	
end

app/models/norma.rb
class Norma < ApplicationRecord
end

app/models/objetos_mensura.rb
class ObjetosMensura < ApplicationRecord
end

app/models/origenes_accion.rb
class Origenes_Accion < ApplicationRecord
end

app/models/parcela.rb
class Parcela < ApplicationRecord
	belongs_to :propiedad
	has_many :mensuras, -> { order(:mensura_nro) }
	#accepts_nested_attributes_for :mensuras, reject_if: :all_blank, allow_destroy: true
end

app/models/propiedad.rb
class Propiedad < ApplicationRecord
	has_one :parcela
	belongs_to :localidad
	belongs_to :jurisdiccion
	belongs_to :departamento, optional: true

	
end

app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord
	self.table_name = 'tipos_documentos'
end

app/models/tipo_expediente.rb
class TipoExpediente < ApplicationRecord
  self.table_name = 'tipos_expedientes'
end

app/models/visador.rb
class Visador < ApplicationRecord
		belongs_to :tipo_documento, optional: true, foreign_key: :tipos_documento_id
		validates :tipos_documento_id, presence: true
	  validates :matricula, presence: true
    validates :apellido, presence: true
    validates :nombre, presence: true
    validates :documento, presence: true
    validates :zona, presence: true

		
end

app/controllers/objetos_mensuras_controller.rb
class ObjetosMensurasController < ApplicationController
  before_action :set_objetos_mensura, only: [:show, :edit, :update, :destroy]

  # GET /objetos_mensuras
  # GET /objetos_mensuras.json
  def index
    @objetos_mensuras = ObjetosMensura.all
  end

  # GET /objetos_mensuras/1
  # GET /objetos_mensuras/1.json
  def show
  end

  # GET /objetos_mensuras/new
  def new
    @objetos_mensura = ObjetosMensura.new
  end

  # GET /objetos_mensuras/1/edit
  def edit
  end

  # POST /objetos_mensuras
  # POST /objetos_mensuras.json
  def create
    @objetos_mensura = ObjetosMensura.new(objetos_mensura_params)

    respond_to do |format|
      if @objetos_mensura.save
        format.html { redirect_to @objetos_mensura, notice: 'Objetos mensura was successfully created.' }
        format.json { render :show, status: :created, location: @objetos_mensura }
      else
        format.html { render :new }
        format.json { render json: @objetos_mensura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objetos_mensuras/1
  # PATCH/PUT /objetos_mensuras/1.json
  def update
    respond_to do |format|
      if @objetos_mensura.update(objetos_mensura_params)
        format.html { redirect_to @objetos_mensura, notice: 'Objetos mensura was successfully updated.' }
        format.json { render :show, status: :ok, location: @objetos_mensura }
      else
        format.html { render :edit }
        format.json { render json: @objetos_mensura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objetos_mensuras/1
  # DELETE /objetos_mensuras/1.json
  def destroy
    @objetos_mensura.destroy
    respond_to do |format|
      format.html { redirect_to objetos_mensuras_url, notice: 'Objetos mensura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objetos_mensura
      @objetos_mensura = ObjetosMensura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objetos_mensura_params
      params.require(:objetos_mensura).permit(:descripcion)
    end
end

app/helpers/mensuras_helper.rb
module MensurasHelper
end

app/helpers/objetos_mensuras_helper.rb
module ObjetosMensurasHelper
end

app/helpers/parcelas_helper.rb
module ParcelasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/objetos_mensuras/_form.html.erb
<%= form_for(objetos_mensura) do |f| %>
  <% if objetos_mensura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objetos_mensura.errors.count, "error") %> prohibited this objetos_mensura from being saved:</h2>

      <ul>
      <% objetos_mensura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/objetos_mensuras/edit.html.erb
<h1>Editing Objetos Mensura</h1>

<%= render 'form', objetos_mensura: @objetos_mensura %>

<%= link_to 'Show', @objetos_mensura %> |
<%= link_to 'Back', objetos_mensuras_path %>

app/views/objetos_mensuras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Objetos Mensuras</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @objetos_mensuras.each do |objetos_mensura| %>
      <tr>
        <td><%= objetos_mensura.descripcion %></td>
        <td><%= link_to 'Show', objetos_mensura %></td>
        <td><%= link_to 'Edit', edit_objetos_mensura_path(objetos_mensura) %></td>
        <td><%= link_to 'Destroy', objetos_mensura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Objetos Mensura', new_objetos_mensura_path %>

app/views/objetos_mensuras/new.html.erb
<h1>New Objetos Mensura</h1>

<%= render 'form', objetos_mensura: @objetos_mensura %>

<%= link_to 'Back', objetos_mensuras_path %>

app/views/objetos_mensuras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @objetos_mensura.descripcion %>
</p>

<%= link_to 'Edit', edit_objetos_mensura_path(@objetos_mensura) %> |
<%= link_to 'Back', objetos_mensuras_path %>