config/routes.rb
Rails.application.routes.draw do
  resources :localidades do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :iniciadores do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :objetos_mensuras
  resources :mensuras do
    member do
      get :reporte
    end
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :expedientes do
    collection do
         get :busqueda
         get :asignar
         post :resultado_busqueda
    end
  end
  resources :propiedades do
    collection do
      get :consulta
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
    member do
      get :mensuras
    end
  end
  resources :parcelas do
    collection do
      get :mensuraPar
      post :guardar_mensuras
    end
  end
  resources :visadores do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :jurisdicciones do
    member do
      get :get_mensure_attributes #  /jurisdicciones/:id/get_mensure_attributes
    end
  end
  resources :departamentos
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/barrio.rb
class Barrio < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
	has_many :localidad
	has_many :mensura
end

app/models/expediente.rb
class Expediente < ApplicationRecord
	belongs_to :tipo_expediente
	has_one :mensura

	def fecha_to_s
		fecha.strftime('%d-%m-%Y')
	end
end

app/models/iniciador.rb
class Iniciador < ApplicationRecord
	belongs_to :tipo_documento
	validates :tipo_documento_id, presence: true
	validates :matricula, presence: true
  validates :razon_social, presence: true
 end

app/models/jurisdiccion.rb
class Jurisdiccion < ApplicationRecord
  belongs_to :departamento
  has_many :mensura

  def caracter
  	LetraMensura.where(codigo: departamento_id).first.letra_mensura
  end

  def number
  	mensura = Mensura.where(mensura_letra: caracter).order(mensura_nro: :desc).first
  	if mensura
  	  mensura.mensura_nro
  	else
  	  0
  	end
  end
end

app/models/letra_mensura.rb
class LetraMensura < ApplicationRecord
  self.table_name = "letra_mensura"
end

app/models/localidad.rb
class Localidad < ApplicationRecord
	belongs_to :departamento
end

app/models/logs_accion.rb
class Logs_Accion < ApplicationRecord
end

app/models/manzana.rb
class Manzana < ApplicationRecord
end

app/models/mensura.rb
class Mensura < ApplicationRecord
	belongs_to :jurisdiccion
	belongs_to :expediente, foreign_key: :expte_id, optional: true
	belongs_to :rectificacion, foreign_key: :rectificacion_id, optional: true, class_name: 'Mensura'
	belongs_to :iniciador, optional: true
	belongs_to :localidad, optional: true
	belongs_to :visador, optional: true
	belongs_to :objetos_mensura, optional: true, foreign_key: :objeto_id
	belongs_to :departamento, optional: true
	belongs_to :parcela, optional: true
	validates :jurisdiccion_id, :objeto_id, :fecha_registracion, presence: true

	
end

app/models/norma.rb
class Norma < ApplicationRecord
end

app/models/objetos_mensura.rb
class ObjetosMensura < ApplicationRecord
end

app/models/origenes_accion.rb
class Origenes_Accion < ApplicationRecord
end

app/models/parcela.rb
class Parcela < ApplicationRecord
	belongs_to :propiedad
	has_many :mensuras, -> { order(:mensura_nro) }
	#accepts_nested_attributes_for :mensuras, reject_if: :all_blank, allow_destroy: true
end

app/models/propiedad.rb
class Propiedad < ApplicationRecord
	has_one :parcela
	belongs_to :localidad
	belongs_to :jurisdiccion
	belongs_to :departamento, optional: true

	
end

app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord
	self.table_name = 'tipos_documentos'
end

app/models/tipo_expediente.rb
class TipoExpediente < ApplicationRecord
  self.table_name = 'tipos_expedientes'
end

app/models/visador.rb
class Visador < ApplicationRecord
		belongs_to :tipo_documento, optional: true, foreign_key: :tipos_documento_id
		validates :tipos_documento_id, presence: true
	  validates :matricula, presence: true
    validates :apellido, presence: true
    validates :nombre, presence: true
    validates :documento, presence: true
    validates :zona, presence: true

		
end

app/controllers/mensuras_controller.rb
class MensurasController < ApplicationController
  before_action :set_mensura, only: [:show, :edit, :update, :destroy, :asignar]

  # GET /mensuras
  # GET /mensuras.json
  def index
    @mensuras = Mensura.paginate(page: params[:page], per_page:10).all.order(fecha_registracion: :desc)
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'mensuras/reporte', pdf:'reporte'}
    end
  end

  # GET /mensuras/1
  # GET /mensuras/1.json
  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf {render layout: 'pdfs', template: 'mensuras/reporte', pdf:'reporte'}
    end
  end

  # GET /mensuras/new
  def new
    @mensura = Mensura.new
    if params[:fancybox]  
      render(layout: false)
    end
  end

  # GET /mensuras/1/edit
  def edit
    @expediente = @mensura.expediente
  end

  # POST /mensuras
  # POST /mensuras.json
  def create
    @mensura = Mensura.new(mensura_params)
    
    respond_to do |format|
      if @mensura.save
        format.html { redirect_to edit_mensura_path @mensura, notice: 'El registro se almacenó correctamente' }
        format.json { render :show, status: :created, location: @mensura }
        format.js { render(template: 'asignar') }
      else
        format.html { render :new }
        format.json { render json: @mensura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mensuras/1
  # PATCH/PUT /mensuras/1.json
  def update
    respond_to do |format|
      if @mensura.update(mensura_params)
        format.html { redirect_to mensura_path(@mensura), notice: 'El registro se actualizó correctamente' }
        format.json { render :show, status: :ok, location: @mensura }
      else
        format.html { render :edit }
        format.json { render json: @mensura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensuras/1
  # DELETE /mensuras/1.json
  def destroy
    @mensura.destroy
    respond_to do |format|
      format.html { redirect_to mensuras_url, notice: 'El registro se eliminó correctamente' }
      format.json { head :no_content }
    end
  end

  def reporte
    respond_to do |format|
      format.html {render(layout: pdfs)}
      format.json
      format.pdf {render layout: 'pdfs', template: 'mensuras/reporte', pdf:'reporte'}
    end
  end

  def busqueda
    #respond_to do |format|
    #  format.html { render(layout: false) }
    #end
    render(layout: false)
  end

 
  def resultado_busqueda
    @mensuras = Mensura.where('mensura_nro::text ilike ?', "%#{params[:mensuras][:numero]}%")
  end

  def asignar
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensura
      @mensura = Mensura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mensura_params
      params.require(:mensura).permit(:mensura_nro,
                                      :mensura_letra,
                                      :objeto_id,
                                      :localidad_id,
                                      :jurisdiccion_id,
                                      :rectificacion_id,
                                      :iniciador_id,
                                      :fecha_operaciones,
                                      :fecha_registracion,
                                      :expte_id,
                                      :visador_id,
                                      :calle,
                                      :propietario)
    end
end

app/helpers/mensuras_helper.rb
module MensurasHelper
end

app/helpers/parcelas_helper.rb
module ParcelasHelper
end

app/helpers/visadores_helper.rb
module VisadoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/mensuras/_form.html.erb
<%= form_for(mensura) do |f| %>
  <% if mensura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mensura.errors.count, "error") %> prohibited this mensura from being saved:</h2>

      <ul>
      <% mensura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="ui-widget ui-widget-content ui-corner-all" id="fconsulta">
      <table id="form-horizontal">
        <tbody>
          <tr>
            <th>
              Jurisdicción:
            </th>
            <td>
              <%= f.select :jurisdiccion_id, options_for_select(Jurisdiccion.all.order(:descripcion).map{|j| [j.descripcion, j.id] }), prompt: "-- Seleccione --"  %>&nbsp;&nbsp;
            </td>
            <th>
              Nro Mensura:
            </th>
            <td>
              <%= f.number_field :mensura_nro %>&nbsp;&nbsp;
            </td>
             <th>
             Letra Mensura:
            </th>
            <td>
              <%= f.text_field :mensura_letra %>
              
            </td>
          </tr>
           <tr>
            <th>
              Objeto Mensura:
            </th>
            <td>
              <%= f.select :objeto_id, options_for_select(ObjetosMensura.all.order(:descripcion).map{|o| [o.descripcion, o.id] }), prompt: "-- Seleccione --" %>&nbsp;&nbsp;
            </td>
            <th>
              Fecha de Registración:
            </th>
            <td>
              <%= f.date_field :fecha_registracion, order: [:day, :month, :year] %>
              <%= image_tag("calendar.png", class: "ui-datepicker-trigger") %>&nbsp;&nbsp;
            </td>
             <th>
             Rectifica Mensura N°:
            </th>
            <td>
               <%= f.hidden_field :rectificacion_id %>
               <%= number_field_tag :rectificacion_nro %>
               <%= link_to image_tag("zoom.png", alt: 'Busqueda'), busqueda_mensuras_path, class: 'fancybox-min' %>
            </td>
          </tr>
        </tbody>
      </table>
    </fieldset>&nbsp;&nbsp;

    <%= render 'relacion_expte/relacionExpte' %>

<script type="text/javascript">
  $(document).ready(function () {
    $('.fancybox-min').fancybox();
  })
</script>
<!-- 
<div class="field">
    <%= f.label :mensura_nro %>
    <%= f.number_field :mensura_nro %>
  </div>

  <div class="field">
    <%= f.label :mensura_letra %>
    <%= f.text_field :mensura_letra %>
  </div>

  <div class="field">
    <%= f.label :objeto_id %>
    
  </div>

  <div class="field">
    <%= f.label :localidad_id %>
    <%= f.number_field :localidad_id %>
  </div>

  <div class="field">
    <%= f.label :jurisdiccion %>
    
  </div>

  <div class="field">
    <%= f.label :rectificacion_id %>
    <%= f.number_field :rectificacion_id %>
  </div>

  <div class="field">
    <%= f.label :iniciador_id %>
    <%= f.number_field :iniciador_id %>
  </div>

  <div class="field">
    <%= f.label :fecha_operaciones %>
    <%= f.date_select :fecha_operaciones %>
  </div>

  <div class="field">
    <%= f.label :fecha_registracion %>
    <%= f.date_select :fecha_registracion %>
  </div>

  <div class="field">
    <%= f.label :expte_id %>
    <%= f.number_field :expte_id %>
  </div>

  <div class="field">
    <%= f.label :visador_id %>
    <%= f.number_field :visador_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
-->
<% end %>

app/views/mensuras/_formEdit.html.erb
<%= form_for(mensura) do |f| %>
  <% if mensura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mensura.errors.count, "error") %> prohibited this mensura from being saved:</h2>

      <ul>
      <% mensura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="ui-widget ui-widget-content ui-corner-all" id="fconsulta">
      <table id="form-horizontal">
        <tbody>
          <tr>
            <th>
              Agrimensor Actuante:
            </th>
            <td>
              <%= f.hidden_field :iniciador_id %>
              <%= text_field_tag :razon_social, mensura.iniciador.try(:razon_social) %>
              <%= link_to image_tag("zoom.png", alt: 'Busqueda'), busqueda_iniciadores_path, class: 'fancybox-min' %>
              <%#= image_tag("add.png") %>
              <%= link_to image_tag("add.png", alt: 'Alta'), new_iniciador_path(fancybox: true), class: 'fancybox-min' %>
            </td>
            <th>
              Fecha Ingreso Expediente:
            </th>
            <td>
              <%= mensura.expediente.try :fecha_to_s %>
            </td>
            <th>
             Localidad:
            </th>
            <td>
              <%= f.hidden_field :localidad_id%>
              <%= text_field_tag :localidad, mensura.localidad.try(:descripcion) %>
              <%= link_to image_tag("zoom.png", alt: 'Busqueda'), busqueda_localidades_path, class: 'fancybox-min' %>
            </td>
            <th>
              Visador:
            </th>
            <td>
              <%= f.hidden_field :visador_id %>
              <%= text_field_tag :apellido, mensura.visador.try(:apellido) %>
              <%= link_to image_tag("zoom.png", alt: 'Busqueda'), busqueda_visadores_path, class: 'fancybox-min' %>
              <%#= image_tag("add.png") %>
              <%= link_to image_tag("add.png", alt: 'Alta'), new_visador_path(fancybox: true), class: 'fancybox-min' %>
            </td>
          </tr>
           <tr>
            <th>
              Departamento:
            </th>
            <td>
              <%=text_field_tag :departamento, mensura.localidad.try(:departamento).try(:descripcion)  %>&nbsp;
            </td>
            <th>
              Fecha de las operaciones:
            </th>
            <td>
              <%= f.date_field :fecha_operaciones, order: [:day, :month, :year] %>
              <%= image_tag("calendar.png", class: "ui-datepicker-trigger") %>&nbsp;&nbsp;
            </td>             
          </tr>
          <tr>
            <th>
             Propietario o Poseedor: 
            </th>
            <td>
              <%=f.text_field :propietario %>
            </td>
            <th>
             Calle o Paraje:
            </th>
            <td>
              <%= f.text_field :calle %>&nbsp;&nbsp;
            </td>
          </tr>
        </tbody>
      </table>
    </fieldset>&nbsp;&nbsp;

    <%= render 'relacion_expte/relacionExpte' %>

<script type="text/javascript">
  $(document).ready(function () {
    $('.fancybox-min').fancybox();
  })
</script>
<!-- 
<div class="field">
    <%= f.label :mensura_nro %>
    <%= f.number_field :mensura_nro %>
  </div>

  <div class="field">
    <%= f.label :mensura_letra %>
    <%= f.text_field :mensura_letra %>
  </div>

  <div class="field">
    <%= f.label :objeto_id %>
    
  </div>

  <div class="field">
    <%= f.label :localidad_id %>
    <%= f.number_field :localidad_id %>
  </div>

  <div class="field">
    <%= f.label :jurisdiccion %>
    
  </div>

  <div class="field">
    <%= f.label :rectificacion_id %>
    <%= f.number_field :rectificacion_id %>
  </div>

  <div class="field">
    <%= f.label :iniciador_id %>
    <%= f.number_field :iniciador_id %>
  </div>

  <div class="field">
    <%= f.label :fecha_operaciones %>
    <%= f.date_select :fecha_operaciones %>
  </div>

  <div class="field">
    <%= f.label :fecha_registracion %>
    <%= f.date_select :fecha_registracion %>
  </div>

  <div class="field">
    <%= f.label :expte_id %>
    <%= f.number_field :expte_id %>
  </div>

  <div class="field">
    <%= f.label :visador_id %>
    <%= f.number_field :visador_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
-->
<% end %>

app/views/mensuras/_resultado.html.erb
<% unless @mensuras.blank?%>
  <table  class="listado">
    <tr class="ui-widget-header listadoTitulo">
      <th>Numero</th>
      <th>Letra</th>
      <th></th>
    </tr>
    <%  @mensuras.each do |mensura| %>
      <tr class="<%= cycle('par','impar') %>">
        <td><%= mensura.mensura_nro %></td>
        <td><%= mensura.mensura_letra %></td>
        <td>
          <%= button_to 'Asignar', asignar_mensuras_path(id: mensura), method: :get ,remote: true %>
        </td>
      </tr>
    <% end %>
  </table>

<% else %>
  No se encontraron mensuras seg&uacute;n el criterio de b&uacute;squeda.
<% end %>

app/views/mensuras/asignar.js.erb
$("#mensura_rectificacion_id").val('<%= @mensura.id %>');
$("#mensura_id").val('<%= @mensura.id %>');
$("#rectificacion_nro").val('<%= @mensura.mensura_nro %>');
$("#mensura_nro").val('<%= @mensura.mensura_nro %>');
$("#mensura_letra").val('<%= @mensura.mensura_letra %>');

$.fancybox.close();

app/views/mensuras/busqueda.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all">
  <legend class="ui-widget ui-widget-header ui-corner-all">Buscar Mensura</legend>  
  <!--<h1>Buscar Mensura</h1>-->
  <div id='form_mensuras'>
    <%= form_for "mensuras", url: resultado_busqueda_mensuras_path, remote: true do |f| %>
      <!--<div class="field">
        <%= f.label :numero %>
        <%= f.text_field :numero %>&nbsp;&nbsp;
      </div>
      <div class="actions">
        <%= f.submit "Buscar"%>
      </div>-->

      <table id="form-horizontal">
        <tbody>
          <tr>
            <th>
              Nro Mensura:
            </th>
            <td>
              <%= f.text_field :numero %>&nbsp;&nbsp;
            </td>
            <td>
              <%= f.submit "Buscar"%>&nbsp;&nbsp;
            </td>
          </tr>          
        </tbody>
      </table>
    <% end %>
  </div>
  <div id="resultado"></div>
</fieldset>

app/views/mensuras/edit.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" id="edit">
  <legend class="ui-widget ui-widget-header ui-corner-all">Mensura N°: <%= @mensura.mensura_nro %> - <%= @mensura.mensura_letra %></legend>
		<%= render 'formEdit', mensura: @mensura %>
</fieldset>

<%#= link_to 'Show', @mensura %> 
<%#= link_to 'Back', mensuras_path %>

app/views/mensuras/index.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" >
<legend class="ui-widget ui-widget-header ui-corner-all">Mensuras</legend>
<p id="notice"><%= notice %></p>

<table class="listado" id="form-horizontal" >
  <thead>
    <tr class="ui-widget-header listadoTitulo">
      <th>Mensura N°</th>
      <th>Letra</th>
      <th>Expte N°</th>
      <th>Iniciador</th>
      <th>Objeto</th>
      <th>Localidad</th>
      <th>Jurisdiccion</th>
      <th>Rectificacion</th>
      <th>Prop./Poseedor</th>
      <th>Fecha Operaciones</th>
      <th>Visador</th>
      <th>Fecha Registracion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mensuras.each do |mensura| %>
      <tr class="<%= cycle('par','impar') %>">
        <td><%= mensura.mensura_nro %></td>
        <td><%= mensura.mensura_letra %></td>
        <td><%= mensura.expediente.try(:nro_expediente) %></td>
        <td><%= mensura.iniciador.try(:razon_social).try(:upcase) %></td>
        <td><%= mensura.objetos_mensura.try(:descripcion) %></td>
        <td><%= mensura.localidad.try(:descripcion) %></td>
        <td><%= mensura.jurisdiccion.descripcion %></td>
        <td><%= mensura.try(:rectificacion).try(:mensura_nro) %></td>
        <td><%= mensura.propietario.try(:upcase) %></td>
        <td><%= l mensura.fecha_operaciones if mensura.fecha_operaciones %></td>
        <td><%= mensura.visador.try(:apellido).try(:upcase) %></td>
        <td><%= l mensura.fecha_registracion if mensura.fecha_registracion %></td>
        <td><%= link_to image_tag("zoom.png"), mensura %></td>
        <td><%= link_to image_tag("edit.png"), edit_mensura_path(mensura) %></td>
        <td><%= link_to image_tag("delete.png"), mensura, method: :delete, data: { confirm: 'Seguro que desea eliminar la Mensura?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @mensuras %><br>
<%= link_to 'Nueva Mensura', new_mensura_path, class: "submit ui-button ui-widget ui-state-default ui-corner-all" %>
</fieldset>

app/views/mensuras/new.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" id="alta">
  <legend class="ui-widget ui-widget-header ui-corner-all">Alta de Mensuras</legend>
<%= render 'form', mensura: @mensura %>

</fieldset>
<%#= link_to 'Back', mensuras_path %>

app/views/mensuras/reporte.html.erb
<body>
   <div>
   <h1>Mensura: <%= @mensura.mensura_nro %>-<%= @mensura.mensura_letra %></h1>
          <% if @mensura.rectificacion_id %>
          
            Rectifica a la Mensura N°:   
          
          
            <%= @mensura.try(:rectificacion_nro) %>
          
        <%end%>
        
          Localidad:
        
        
          <%= @mensura.localidad.try(:descripcion) if @mensura.localidad_id %>&nbsp;&nbsp;
        
        
          Jurisdiccion:
        
        
          <%= @mensura.jurisdiccion.descripcion %>&nbsp;&nbsp;
        
        
          Calle o Paraje:
        
        
          <%= @mensura.calle.upcase %>&nbsp;&nbsp;
        
          Iniciador:
      
          <%= @mensura.iniciador.try(:razon_social) %>&nbsp;&nbsp;  
    
          Fecha de Registración:
     
          <%= l @mensura.fecha_registracion %>&nbsp;&nbsp;
    
          Propietario/Poseedor:
      
          <%= @mensura.propietario.upcase %>&nbsp;&nbsp;
      
          Expediente N°:
      
          <%= @mensura.expediente.try(:nro_expediente) %>&nbsp;&nbsp;  
        
          Fecha de las Operaciones:
    
          <%= l @mensura.fecha_operaciones %>  &nbsp;&nbsp;

          Objeto:    
     
          <%= @mensura.objetos_mensura.try(:descripcion) %>&nbsp;&nbsp;  
     
          Agrimensor Visador:
     
          <%= @mensura.visador.try(:apellido).upcase %>&nbsp;&nbsp;
    
      </div>            
</body>

app/views/mensuras/reporte.pdf.erb

   <div class="main">
   <h1>Mensura: <%= @mensura.try(:mensura_nro) %>-<%= @mensura.try(:mensura_letra) %></h1>

   <br><br>

   
    <b>Rectifica a la Mensura N°:</b>   
    	<%= @mensura.try(:rectificacion).try(:mensura_nro) %>
    
    <br><br>

   <b>Expediente N°:</b>
    <%= @mensura.expediente.try(:nro_expediente) %>&nbsp;&nbsp;

    <br><br>

    <b>Iniciador:</b>
    <%= @mensura.iniciador.try(:razon_social) %>&nbsp;&nbsp; 

    <br><br>

		<b>Propietario/Poseedor:</b>
  	<%= @mensura.propietario.try(:upcase) %>&nbsp;&nbsp;
		
		<br><br> 

    <b>Localidad:</b>
    <%= @mensura.localidad.try(:descripcion) if @mensura.localidad_id %>&nbsp;&nbsp;
        
	  <b>Jurisdiccion:</b>
	  <%= @mensura.jurisdiccion.descripcion %>&nbsp;&nbsp;
	        
	  <b>Calle o Paraje:</b>
	  <%= @mensura.calle.try(:upcase) %>&nbsp;&nbsp;
		

		<br><br>
	          
	  <b>Fecha de las Operaciones:</b>
	  <%= l @mensura.fecha_operaciones %>  &nbsp;&nbsp;

	  <b>Objeto:</b>    
	  <%= @mensura.objetos_mensura.try(:descripcion) %>&nbsp;&nbsp; 

	  <br><br>
	     
	  <b>Agrimensor Visador:</b>
	  <%= @mensura.visador.try(:apellido).try(:upcase) %>&nbsp;&nbsp;

	  <br><br>
	  
	  	<p align=center><b>Fecha de Registración:</b>
	  	<%= l @mensura.fecha_registracion %></p>
	   
  </div>            

app/views/mensuras/show.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" >
<legend class="ui-widget ui-widget-header ui-corner-all">Mensura: <%= @mensura.try(:mensura_nro) %>-<%= @mensura.try(:mensura_letra) %></legend>
<p id="notice"><%= notice %></p>
  <table>
    <tbody> 
      <tr>
        <% if @mensura.rectificacion_id %>
          <th>
            Rectifica a la Mensura N°:   
          </th>
          <td>
            <%= @mensura.try(:rectificacion).try(:mensura_nro) %>
          </td>
        <%end%>
        <th>
          Localidad:
        </th>
        <td>
          <%= @mensura.localidad.try(:descripcion) if @mensura.localidad_id %>&nbsp;&nbsp;
        </td>
        <th>
          Jurisdiccion:
        </th>
        <td>
          <%= @mensura.jurisdiccion.descripcion %>&nbsp;&nbsp;
        </td>
        <th>
          Calle o Paraje:
        </th>
        <td>
          <%= @mensura.calle.try(:upcase) %>&nbsp;&nbsp;
        </td>
      </tr>
      <tr>
        <th>
          Iniciador:
        </th>
        <td>
          <%= @mensura.iniciador.try(:razon_social).try(:upcase) %>&nbsp;&nbsp;  
        </td>
        <th>
          Fecha de Registración:
        </th>
        <td>
          <%= l @mensura.fecha_registracion %>&nbsp;&nbsp;
        </td>
      </tr>
      <tr>
        <th>
          Propietario/Poseedor:
        </th>
        <td>
          <%= @mensura.propietario.try(:upcase) %>&nbsp;&nbsp;
        </td>
        <th>
          Expediente N°:
        </th>
        <td>
          <%= @mensura.expediente.try(:nro_expediente) %>&nbsp;&nbsp;  
        </td>
        <th>
          Fecha de las Operaciones:
        </th>
        <td>
          <%= l @mensura.fecha_operaciones %>  &nbsp;&nbsp;
        </td>
      </tr>
      <tr>
        <th>
          Objeto:    
        </th>
        <td>
          <%= @mensura.objetos_mensura.try(:descripcion) %>&nbsp;&nbsp;  
        </td>
        <th>
          Agrimensor Visador:
        </th>
        <td>
          <%= @mensura.visador.try(:apellido).try(:upcase) %>&nbsp;&nbsp;
        </td>
      </tr> 
      <tr>
        <td>
         <%= link_to image_tag("edit"), edit_mensura_path(@mensura) %> |
         <%= link_to image_tag("back"), mensuras_path %>
        </td>
        <td style="text-align: center">
          <%= link_to 'Reporte Alta', mensura_path(@mensura, :format => :pdf), class: "submit ui-button ui-widget ui-state-default ui-corner-all", target:"_blank" %>
        </td> 
      </tr>                  
      


</fieldset>