config/routes.rb
Rails.application.routes.draw do
  resources :localidades do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :iniciadores do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :objetos_mensuras
  resources :mensuras do
    member do
      get :reporte
    end
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :expedientes do
    collection do
         get :busqueda
         get :asignar
         post :resultado_busqueda
    end
  end
  resources :propiedades do
    collection do
      get :consulta
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
    member do
      get :mensuras
    end
  end
  resources :parcelas do
    collection do
      get :mensuraPar
      post :guardar_mensuras
    end
  end
  resources :visadores do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :jurisdicciones do
    member do
      get :get_mensure_attributes #  /jurisdicciones/:id/get_mensure_attributes
    end
  end
  resources :departamentos
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/barrio.rb
class Barrio < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
	has_many :localidad
	has_many :mensura
end

app/models/expediente.rb
class Expediente < ApplicationRecord
	belongs_to :tipo_expediente
	has_one :mensura

	def fecha_to_s
		fecha.strftime('%d-%m-%Y')
	end
end

app/models/iniciador.rb
class Iniciador < ApplicationRecord
	belongs_to :tipo_documento
	validates :tipo_documento_id, presence: true
	validates :matricula, presence: true
  validates :razon_social, presence: true
 end

app/models/jurisdiccion.rb
class Jurisdiccion < ApplicationRecord
  belongs_to :departamento
  has_many :mensura

  def caracter
  	LetraMensura.where(codigo: departamento_id).first.letra_mensura
  end

  def number
  	mensura = Mensura.where(mensura_letra: caracter).order(mensura_nro: :desc).first
  	if mensura
  	  mensura.mensura_nro
  	else
  	  0
  	end
  end
end

app/models/letra_mensura.rb
class LetraMensura < ApplicationRecord
  self.table_name = "letra_mensura"
end

app/models/localidad.rb
class Localidad < ApplicationRecord
	belongs_to :departamento
end

app/models/logs_accion.rb
class Logs_Accion < ApplicationRecord
end

app/models/manzana.rb
class Manzana < ApplicationRecord
end

app/models/mensura.rb
class Mensura < ApplicationRecord
	belongs_to :jurisdiccion
	belongs_to :expediente, foreign_key: :expte_id, optional: true
	belongs_to :rectificacion, foreign_key: :rectificacion_id, optional: true, class_name: 'Mensura'
	belongs_to :iniciador, optional: true
	belongs_to :localidad, optional: true
	belongs_to :visador, optional: true
	belongs_to :objetos_mensura, optional: true, foreign_key: :objeto_id
	belongs_to :departamento, optional: true
	belongs_to :parcela, optional: true
	validates :jurisdiccion_id, :objeto_id, :fecha_registracion, presence: true

	
end

app/models/norma.rb
class Norma < ApplicationRecord
end

app/models/objetos_mensura.rb
class ObjetosMensura < ApplicationRecord
end

app/models/origenes_accion.rb
class Origenes_Accion < ApplicationRecord
end

app/models/parcela.rb
class Parcela < ApplicationRecord
	belongs_to :propiedad
	has_many :mensuras, -> { order(:mensura_nro) }
	#accepts_nested_attributes_for :mensuras, reject_if: :all_blank, allow_destroy: true
end

app/models/propiedad.rb
class Propiedad < ApplicationRecord
	has_one :parcela
	belongs_to :localidad
	belongs_to :jurisdiccion
	belongs_to :departamento, optional: true

	
end

app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord
	self.table_name = 'tipos_documentos'
end

app/models/tipo_expediente.rb
class TipoExpediente < ApplicationRecord
  self.table_name = 'tipos_expedientes'
end

app/models/visador.rb
class Visador < ApplicationRecord
		belongs_to :tipo_documento, optional: true, foreign_key: :tipos_documento_id
		validates :tipos_documento_id, presence: true
	  validates :matricula, presence: true
    validates :apellido, presence: true
    validates :nombre, presence: true
    validates :documento, presence: true
    validates :zona, presence: true

		
end

app/controllers/visadores_controller.rb
class VisadoresController < ApplicationController
  before_action :set_visador, only: [:show, :edit, :update, :destroy, :asignar]

  # GET /visadores
  # GET /visadores.json
  def index
    @visadores = Visador.paginate(page: params[:page], per_page:10).all.order(:apellido)
  end

  # GET /visadores/1
  # GET /visadores/1.json
  def show
  end

  # GET /visadores/new
  def new
    @visador = Visador.new
    if params[:fancybox]
      render(layout: false)
    end
  end

  # GET /visadores/1/edit
  def edit
  end

  # POST /visadores
  # POST /visadores.json
  def create
    @visador = Visador.new(visador_params)

    respond_to do |format|
      if @visador.save
        format.html { redirect_to @visador, notice: 'Visador creado correctamente.' }
        format.json { render :show, status: :created, location: @visador }
        format.js {render template: 'visadores/asignar'}
      else
        format.html { render :new }
        format.json { render json: @visador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visadores/1
  # PATCH/PUT /visadores/1.json
  def update
    respond_to do |format|
      if @visador.update(visador_params)
        format.html { redirect_to @visador, notice: 'Visador guardado correctamente.' }
        format.json { render :show, status: :ok, location: @visador }
      else
        format.html { render :edit }
        format.json { render json: @visador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visadores/1
  # DELETE /visadores/1.json
  def destroy
    @visador.destroy
    respond_to do |format|
      format.html { redirect_to visadores_url, notice: 'Visador eliminado correctamente.' }
      format.json { head :no_content }
    end
  end
  def busqueda
    #respond_to do |format|
    #  format.html { render(layout: false) }
    #end
    render(layout: false)
  end

 
  def resultado_busqueda
    @visadores = Visador.where('apellido ilike ?', "%#{params[:visador][:apellido]}%")
  end

  def asignar
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visador
      @visador = Visador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visador_params
      params.require(:visador).permit(:apellido, :nombre, :tipos_documento_id, :documento, :matricula, :zona)
    end
end

app/helpers/mensuras_helper.rb
module MensurasHelper
end

app/helpers/visadores_helper.rb
module VisadoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/visadores/_form.html.erb
<%= form_for(visador, remote: params[:fancybox]) do |f| %>
  <% if visador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visador.errors.count, "error") %> prohibited this visador from being saved:</h2>

      <ul>
      <% visador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table id="form-horizontal">
    <tbody>
      <tr>
        <th>      
          Apellido:          
        </th>
        <td>
          <%= f.text_field :apellido %>&nbsp;&nbsp;
        </td>
        <th>
          Nombre:
        </th>
        <td>
          <%= f.text_field :nombre %>&nbsp;&nbsp;  
        </td>
        <th>
          Tipo Documento:
        </th>
        <td>
          <%= f.select :tipos_documento_id, options_for_select(TipoDocumento.all.order(:descripcion).map{|j| [j.descripcion, j.id] }), prompt: "-- Seleccione --" %>&nbsp;&nbsp;
        </td>
        <th>
          Número:
        </th>
        <td>
          <%= f.text_field :documento %>&nbsp;&nbsp;  
        </td>
      </tr>
      <tr>        
        <th>
          Matrícula:
        </th>
        <td>
          <%= f.text_field :matricula %>&nbsp;&nbsp;  
        </td>
        <th>
          Zona N°:
        </th>
        <td>
          <%= f.number_field :zona %>&nbsp;&nbsp;  
        </td>
      </tr>
    </tbody>
  </table>
  <div style="text-align: center">
      <input class="submit ui-button ui-widget ui-state-default ui-corner-all" name="commit" type="submit" value="Guardar" role="button" aria-disabled="false">&nbsp; &nbsp;
  </div>
<% end %>

app/views/visadores/_resultado.html.erb
<% unless @visadores.blank?%>
  <table  class="listado">
    <tr class="ui-widget-header listadoTitulo">
      
      <th>Agrimensor Visador</th>
      <th></th>
    </tr>
    <%  @visadores.each do |visador| %>
      <tr class="<%= cycle('par','impar') %>">
        <td><%= visador.apellido.upcase %></td>
      
        <td>
          <%= button_to 'Asignar', asignar_visadores_path(id: visador), method: :get ,remote: true %>
        </td>
      </tr>
    <% end %>
  </table>

<% else %>
  No se encontraron visadores seg&uacute;n el criterio de b&uacute;squeda.
<% end %>

app/views/visadores/asignar.js.erb
$("#mensura_visador_id").val('<%= @visador.id %>');
$("#apellido").val('<%= @visador.apellido %>');
$.fancybox.close();

app/views/visadores/busqueda.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all">
  <legend class="ui-widget ui-widget-header ui-corner-all">Buscar Agrimensor Visador</legend>  
  <!--<h1>Buscar Mensura</h1>-->
  <div id='form_visador'>
    <%= form_for "visador", url: resultado_busqueda_visadores_path, remote: true do |f| %>
     

      <table id="form-horizontal">
        <tbody>
          <tr>
            <th>
              Apellido:
            </th>
            <td>
              <%= f.text_field :apellido %>&nbsp;&nbsp;
            </td>
            <td>
              <%= f.submit "Buscar"%>&nbsp;&nbsp;
            </td>
          </tr>          
        </tbody>
      </table>
    <% end %>
  </div>
  <div id="resultado"></div>
</fieldset>

app/views/visadores/edit.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" >
<legend class="ui-widget ui-widget-header ui-corner-all">Editar Agrimensor Visador</legend>

<%= render 'form', visador: @visador %>

<%#= link_to 'Show', @visador %> 
<%#= link_to 'Back', visadores_path %>
</fieldset>

app/views/visadores/index.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" >
<legend class="ui-widget ui-widget-header ui-corner-all">Agrimensor Visador</legend>
<p id="notice"><%= notice %></p>

<table class="listado" id="form-horizontal">
  <thead>
    <tr class="ui-widget-header listadoTitulo">
      <th>Apellido</th>
      <th>Nombre</th>
      <th>Tipos documento</th>
      <th>Documento</th>
      <th>Matricula</th>
      <th>Zona</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visadores.each do |visador| %>
      <tr class="<%= cycle('par','impar') %>">
        <td><%= visador.apellido.upcase %></td>
        <td><%= visador.nombre.upcase %></td>
        <td><%= visador.tipo_documento.try(:descripcion_corta) %></td>
        <td><%= visador.documento %></td>
        <td><%= visador.matricula %></td>
        <td><%= visador.zona %></td>
        <td><%= link_to image_tag("zoom.png"), visador %></td>
        <td><%= link_to image_tag("edit.png"), edit_visador_path(visador) %></td>
        <td><%= link_to image_tag("delete.png"), visador, method: :delete, data: { confirm: 'Esta seguro que desea eliminar este visador?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @visadores %><br>
<%= link_to 'Nuevo Visador', new_visador_path, class: "submit ui-button ui-widget ui-state-default ui-corner-all" %>

app/views/visadores/new.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" >
<legend class="ui-widget ui-widget-header ui-corner-all">Nuevo Agrimensor Visador</legend>
<%= render 'form', visador: @visador %>
</fieldset>
<%#= link_to 'Back', visadores_path %>

app/views/visadores/show.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" >
<legend class="ui-widget ui-widget-header ui-corner-all">Agrimensor Actuante</legend>
<p id="notice"><%= notice %></p>

<p>
  <strong>Apellido:</strong>
  <%= @visador.apellido.upcase %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @visador.nombre.upcase %>
</p>

<p>
  <strong>Tipos documento:</strong>
  <%= @visador.tipo_documento.try(:descripcion_corta) %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @visador.documento %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @visador.matricula %>
</p>

<p>
  <strong>Zona:</strong>
  <%= @visador.zona %>
</p>

<%= link_to image_tag("edit"), edit_visador_path(@visador) %> 
<%= link_to image_tag("back"), visadores_path %>
</fieldset>