config/routes.rb
Rails.application.routes.draw do
  resources :localidades do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :iniciadores do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :objetos_mensuras
  resources :mensuras do
    member do
      get :reporte
    end
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :expedientes do
    collection do
         get :busqueda
         get :asignar
         post :resultado_busqueda
    end
  end
  resources :propiedades do
    collection do
      get :consulta
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
    member do
      get :mensuras
    end
  end
  resources :parcelas do
    collection do
      get :mensuraPar
      post :guardar_mensuras
    end
  end
  resources :visadores do
    collection do
      get :busqueda
      get :asignar
      post :resultado_busqueda
    end
  end
  resources :jurisdicciones do
    member do
      get :get_mensure_attributes #  /jurisdicciones/:id/get_mensure_attributes
    end
  end
  resources :departamentos
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/barrio.rb
class Barrio < ApplicationRecord
end

app/models/departamento.rb
class Departamento < ApplicationRecord
	has_many :localidad
	has_many :mensura
end

app/models/expediente.rb
class Expediente < ApplicationRecord
	belongs_to :tipo_expediente
	has_one :mensura

	def fecha_to_s
		fecha.strftime('%d-%m-%Y')
	end
end

app/models/iniciador.rb
class Iniciador < ApplicationRecord
	belongs_to :tipo_documento
	validates :tipo_documento_id, presence: true
	validates :matricula, presence: true
  validates :razon_social, presence: true
 end

app/models/jurisdiccion.rb
class Jurisdiccion < ApplicationRecord
  belongs_to :departamento
  has_many :mensura

  def caracter
  	LetraMensura.where(codigo: departamento_id).first.letra_mensura
  end

  def number
  	mensura = Mensura.where(mensura_letra: caracter).order(mensura_nro: :desc).first
  	if mensura
  	  mensura.mensura_nro
  	else
  	  0
  	end
  end
end

app/models/letra_mensura.rb
class LetraMensura < ApplicationRecord
  self.table_name = "letra_mensura"
end

app/models/localidad.rb
class Localidad < ApplicationRecord
	belongs_to :departamento
end

app/models/logs_accion.rb
class Logs_Accion < ApplicationRecord
end

app/models/manzana.rb
class Manzana < ApplicationRecord
end

app/models/mensura.rb
class Mensura < ApplicationRecord
	belongs_to :jurisdiccion
	belongs_to :expediente, foreign_key: :expte_id, optional: true
	belongs_to :rectificacion, foreign_key: :rectificacion_id, optional: true, class_name: 'Mensura'
	belongs_to :iniciador, optional: true
	belongs_to :localidad, optional: true
	belongs_to :visador, optional: true
	belongs_to :objetos_mensura, optional: true, foreign_key: :objeto_id
	belongs_to :departamento, optional: true
	belongs_to :parcela, optional: true
	validates :jurisdiccion_id, :objeto_id, :fecha_registracion, presence: true

	
end

app/models/norma.rb
class Norma < ApplicationRecord
end

app/models/objetos_mensura.rb
class ObjetosMensura < ApplicationRecord
end

app/models/origenes_accion.rb
class Origenes_Accion < ApplicationRecord
end

app/models/parcela.rb
class Parcela < ApplicationRecord
	belongs_to :propiedad
	has_many :mensuras, -> { order(:mensura_nro) }
	#accepts_nested_attributes_for :mensuras, reject_if: :all_blank, allow_destroy: true
end

app/models/propiedad.rb
class Propiedad < ApplicationRecord
	has_one :parcela
	belongs_to :localidad
	belongs_to :jurisdiccion
	belongs_to :departamento, optional: true

	
end

app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord
	self.table_name = 'tipos_documentos'
end

app/models/tipo_expediente.rb
class TipoExpediente < ApplicationRecord
  self.table_name = 'tipos_expedientes'
end

app/models/visador.rb
class Visador < ApplicationRecord
		belongs_to :tipo_documento, optional: true, foreign_key: :tipos_documento_id
		validates :tipos_documento_id, presence: true
	  validates :matricula, presence: true
    validates :apellido, presence: true
    validates :nombre, presence: true
    validates :documento, presence: true
    validates :zona, presence: true

		
end

app/controllers/propiedades_controller.rb
class PropiedadesController < ApplicationController
  before_action :set_propiedad, only: [:show, :edit, :update, :destroy, :asignar, :mensuras]

  # GET /propiedades
  # GET /propiedades.json
  def index
    @propiedades = Propiedad.paginate(page: params[:page], per_page:10).all.order(fecha_vigencia: :desc)
    if params[:partida]
      @propiedades = @propiedades.where('partida::text ilike ?', "%#{params[:partida]}%")
    end
  end

  # GET /propiedades/1
  # GET /propiedades/1.json
  def show
  end

  # GET /propiedades/new
  def new
    @propiedad = Propiedad.new
  end

  # GET /propiedades/1/edit
  def edit
  end

  # POST /propiedades
  # POST /propiedades.json
  def create
    @propiedad = Propiedad.new(propiedad_params)

    respond_to do |format|
      if @propiedad.save
        format.html { redirect_to @propiedad, notice: 'Propiedad creada correctamente' }
        format.json { render :show, status: :created, location: @propiedad }
      else
        format.html { render :new }
        format.json { render json: @propiedad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /propiedades/1
  # PATCH/PUT /propiedades/1.json
  def update
    respond_to do |format|
      if @propiedad.update(propiedad_params)
        if params[:mensura_id].present?
          mensura = Mensura.find(params[:mensura_id])
          mensura.update_attributes(parcela_id: @propiedad.parcela.id)
        end
        format.html { redirect_to @propiedad, notice: 'Propiedad guardada correctamente.' }
        format.json { render :show, status: :ok, location: @propiedad }
      else
        format.html { render :edit }
        format.json { render json: @propiedad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /propiedades/1
  # DELETE /propiedades/1.json
  def destroy
    @propiedad.destroy
    respond_to do |format|
      format.html { redirect_to propiedades_url, notice: 'Propiedad eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  def mensuras
    respond_to do |format|
      format.html { render layout: false }
    end
  end

   def resultado_busqueda
      @propiedades = Propiedad.where('partida::text ilike ?', "%#{params[:propiedades][:partida]}%") 
  end
  def asignar
    
  end

  def busqueda
    render(layout: false)
  end
  
  def consulta
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_propiedad
      @propiedad = Propiedad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def propiedad_params
      params.require(:propiedad).permit(:partida, 
                                        :propiedad_union_id, 
                                        :localidad_id, 
                                        :irp_tomo, 
                                        :irp_folio_real, 
                                        :irp_folio_uf, 
                                        :cantidad_ocupantes, 
                                        :fecha_aplicacion_decreto, 
                                        :coeficiente_prorrateo, 
                                        :superficie_unidad_funcional, 
                                        :piso, 
                                        :dpto, 
                                        :propiedad_block_id, 
                                        :tipo_propiedad_id, 
                                        :zona_id, 
                                        :jurisdiccion_id, 
                                        :agua_cte, 
                                        :cloaca, 
                                        :irp_finca, 
                                        :exp_nro, 
                                        :exp_anio, 
                                        :exp_letra, 
                                        :propiedad_origen_id, 
                                        :fecha_vigencia)
    end
end

app/helpers/mensuras_helper.rb
module MensurasHelper
end

app/helpers/propiedades_helper.rb
module PropiedadesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/propiedades/_form.html.erb
<%= form_for(propiedad) do |f| %>
  <% if propiedad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(propiedad.errors.count, "error") %> prohibited this propiedad from being saved:</h2>

      <ul>
      <% propiedad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset class="ui-widget ui-widget-content ui-corner-all" id="fconsulta">
  <table id="form-horizontal">
    <tbody>
      <legend class="ui-widget ui-widget-header ui-corner-all"> Propiedad </legend>
      <table>
        <tr>
          <th>
            <%= f.label :zona_id %>      
          </th>
          <td>
            <%= f.number_field :zona_id %>
          </td>
          <th>
            <%= f.label :jurisdiccion_id %>      
          </th>
          <td>  
            <%= text_field_tag :jurisdiccion, propiedad.jurisdiccion.try(:descripcion) %>
          </td>
          <th>
            <%= f.label :localidad_id %>      
          </th>
          <td>  
            <%= text_field_tag :localidad, propiedad.localidad.try(:descripcion) %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :tipo_propiedad_id %>      
          </th>
          <td>
            <%= f.number_field :tipo_propiedad_id %>
          </td>
          <th>
            <%= f.label :agua_cte %>      
          </th>
          <td>  
            <%= f.check_box :agua_cte %>
          </td>
          <th>
            <%= f.label :cloaca %>      
          </th>
          <td>
            <%= f.check_box :cloaca %>
          </td>
        </tr>  
        <tr>
          <th>
            <%= f.label :piso %>      
          </th>
          <td>
            <%= f.text_field :piso %>
          </td>
          <th>
            <%= f.label :departamento %>      
          </th>
          <td>
            <%= f.text_field :dpto %>
          </td>
          <th>
            <%= f.label :cantidad_ocupantes %>      
          </th>
          <td>
            <%= f.number_field :cantidad_ocupantes %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :propiedad_block_id %>      
          </th>
          <td>
            <%= f.number_field :propiedad_block_id %>
          </td>
          <th>
            <%= f.label :coeficiente_prorrateo %>      
          </th>
          <td>
            <%= f.number_field :coeficiente_prorrateo %>
          </td>
          <th>
            <%= f.label :superficie_unidad_funcional %>      
          </th>
          <td>
            <%= f.number_field :superficie_unidad_funcional %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :fecha_vigencia %>       
          </th>
          <td>
            <%= f.date_field :fecha_vigencia, order: [:day, :month, :year] %>
          </td>
          <th>
             <%= f.label :propiedad_origen_id %>      
          </th>
          <td>
            <%= f.number_field :propiedad_origen_id %>
          </td>          
        </tr>
        </table>
        </fieldset>
        <fieldset class="ui-widget ui-widget-content ui-corner-all" id="fconsulta">
        <legend class="ui-widget ui-widget-header ui-corner-all"> R.P.I </legend>
        <table>
         <tr>
          <th>
            <%= f.label :Tomo %>        
          </th>
          <td>
            <%= f.text_field :irp_tomo %>
          </td>
          <th>
            <%= f.label :Folio %>      
          </th>
          <td>
            <%= f.text_field :irp_folio_real %>/
          </td>
         
          <td>
            <%= f.text_field :irp_folio_uf %>
          </td>
          <th>
            <%= f.label :Finca %>      
          </th>
          <td>
            <%= f.number_field :irp_finca %>
          </td>
         <th>
            <%= f.label :Año %>      
          </th>
          <td>
            <%= f.number_field :irp_anio %>
          </td>
        </tr>
        </table>
        </fieldset>
        <fieldset class="ui-widget ui-widget-content ui-corner-all" id="fconsulta">
        <legend class="ui-widget ui-widget-header ui-corner-all"> Parcela </legend>
        <table>
         <tr>
          <th>
            Sup. Catastro        
          </th>
          <td>
            <%= number_field_tag :superficie_catastro, propiedad.parcela.try(:superficie_catastro) %>
          </td>
          <th>
            Sup. Mensura      
          </th>
          <td>
            <%= number_field_tag :superficie_mensura, propiedad.parcela.try(:superficie_mensura) %>
          </td>
        </tr>
        </table>
        </fieldset>
        <fieldset class="ui-widget ui-widget-content ui-corner-all" id="fconsulta">
        <legend class="ui-widget ui-widget-header ui-corner-all"> Mensura </legend>
        <table>
         <tr>
          <th style="text-align: left;">
            Mensura N°:        
          </th>
          <td>
            <%= number_field_tag :mensura_nro, propiedad.parcela.try(:mensura).try(:mensura_nro) %>
          </td>
          <th>
            Letra:      
          </th>
          <td>
            <%= text_field_tag :mensura_letra, propiedad.parcela.try(:mensura).try(:mensura_letra) %>
            <%= hidden_field_tag :mensura_id, nil %>
            <%= link_to image_tag("zoom.png", alt: 'Busqueda'), busqueda_mensuras_path, class: 'fancybox-min' %>
            <%= link_to image_tag("history.png", alt: 'Busqueda'), mensuras_propiedad_path(propiedad), class: 'fancybox-min' %>
                        
          </td>
          <tr>
          </tr>
            <td>&nbsp;</td>
          <tr>  
            <th>
              Ultima Mensura:
            </th>
            <td>
              <%= propiedad.parcela.try(:mensuras).try(:last).try(:mensura_nro) %> - <%= propiedad.parcela.try(:mensuras).try(:last).try(:mensura_letra) %>
            </td>
          </tr>
        </tr>
        </table>
        </fieldset>
         

    <div class="actions", style="text-align: center">
      <%= f.submit "Guardar", class: "submit ui-button ui-widget ui-state-default ui-corner-all" %>
    </div>
    </tbody>
  </table>
</fieldset>
<% end %>

<script type="text/javascript">
  $(document).ready(function () {
    $('.fancybox-min').fancybox();

  })
  </script>

app/views/propiedades/_resultado.html.erb
<% unless @propiedades.blank?%>
  <table  class="listado">
    <tr class="ui-widget-header listadoTitulo">
      <th>Partida</th>
      >
    </tr>
    <%  @propiedades.each do |propiedad| %>
      <tr class="<%= cycle('par','impar') %>">
        <td><%= propiedad.partida %></td>
        
        <td>
          <%= button_to 'Asignar', asignar_propiedades_path(id: propiedad), method: :get ,remote: true %>
        </td>
      </tr>
    <% end %>
  </table>

<% else %>
  No se encontraron propiedades seg&uacute;n el criterio de b&uacute;squeda.
<% end %>

app/views/propiedades/asignar.js.erb
$("#propiedad_partida").val('<%= @propiedad.partida %>');

$.fancybox.close();

app/views/propiedades/busqueda.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all">
  <legend class="ui-widget ui-widget-header ui-corner-all">Buscar Propiedad</legend>  
  <!--<h1>Buscar Mensura</h1>-->
  <div id='form_propiedades'>
    <%= form_for "propiedades", url: resultado_busqueda_propiedades_path, remote: true do |f| %>
    

      <table id="form-horizontal">
        <tbody>
          <tr>
            <th>
              Propiedad:
            </th>
            <td>
              <%= f.text_field :partida %>&nbsp;&nbsp;
            </td>
            <td>
              <%= f.submit "Buscar"%>&nbsp;&nbsp;
            </td>
          </tr>          
        </tbody>
      </table>
    <% end %>
  </div>
  <div id="resultado"></div>
</fieldset>

app/views/propiedades/consulta.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all">
  <legend class="ui-widget ui-widget-header ui-corner-all">Buscar Propiedad</legend>  
  
      <table id="form-horizontal">
        <tbody>
          <tr>
            <td>
              <%= text_field_tag :partida %>&nbsp;&nbsp;
            </td>
            <td>
              <%= link_to image_tag("zoom.png", alt: 'Busqueda'), busqueda_propiedades_path, class: 'fancybox-min' %>
              
            </td>
          </tr>          
        </tbody>
      </table>
  
  
 

  <script type="text/javascript">
  $(document).ready(function () {
    $('.fancybox-min').fancybox();
  })
</script>

app/views/propiedades/edit.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" id="edit">
  <legend class="ui-widget ui-widget-header ui-corner-all"><%= @propiedad.partida %> </legend>
		<%= render 'form', propiedad: @propiedad %>
</fieldset>


<%#= link_to 'Show', @propiedad %> |
<%#= link_to 'Back', propiedades_path %>

app/views/propiedades/index.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" >
<legend class="ui-widget ui-widget-header ui-corner-all">Propiedades</legend>
<p id="notice"><%= notice %></p>

<form>
  <table id="form-horizontal">
    <tbody>
      <tr>
        <td>
          <%= text_field_tag :partida,params[:partida], placeholder: "Buscar"%>&nbsp;&nbsp;
        </td>
        <td>
          <%= button_tag image_tag("zoom.png", alt: 'Busqueda') %>
          
        </td>
      </tr>          
    </tbody>
  </table>
</form>

<table class="listado" id="form-horizontal">
  <thead>
    <tr class="ui-widget-header listadoTitulo">
      <th>Partida</th>      
      <th>Localidad</th>
      <th>Jurisdiccion</th> 
      <th>Tomo</th>
      <th>Folio </th>
      <th>Año</th>       
      <th>Fecha vigencia</th>
      <th>Sup. Catastro</th>
      <th>Mensura</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @propiedades.each do |propiedad| %>      
      <tr class="<%= cycle('par','impar') %>">
        <td><%= propiedad.partida %></td>        
        <td><%= propiedad.localidad.try(:descripcion) %></td>
        <td><%= propiedad.jurisdiccion.try(:descripcion) %></td>
        <td><%= propiedad.irp_tomo %></td>
        <td><%= propiedad.irp_folio_real %></td>
        <td><%= propiedad.irp_anio %></td> 
        <td><%= l propiedad.fecha_vigencia if propiedad.fecha_vigencia %></td>
        <td><%= propiedad.parcela.try(:superficie_catastro) %></td>
        <td><%= propiedad.parcela.try(:mensuras).try(:last).try(:mensura_nro) %> - <%= propiedad.parcela.try(:mensuras).try(:last).try(:mensura_letra) %></td>
        <td><%= link_to image_tag("zoom.png"), propiedad %></td>
        <td><%= link_to image_tag("edit.png"), edit_propiedad_path(propiedad) %></td>
        <td><%= link_to image_tag("delete.png"), propiedad, method: :delete, data: { confirm: 'Seguro que desea eliminar esta propiedad?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</fieldset>
<br>


  <%= will_paginate @propiedades%><br>
  <%= link_to 'Nueva Propiedad', new_propiedad_path, class: "submit ui-button ui-widget ui-state-default ui-corner-all" %>

app/views/propiedades/mensuras.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all">
  <legend class="ui-widget ui-widget-header ui-corner-all">Historico Mensuras</legend>  
  <!--<h1>Buscar Mensura</h1>-->
  <div id='form_propiedades'>
  
    <table class="listado" id="form-horizontal">
      <tbody>
        <tr class="ui-widget-header listadoTitulo">
          <th>
            Nro:
          </th>
          <th>
            Letra
          </th>
          <th>
            Agrimensor:
          </th>
          <th>
            Fecha de Registración:
          </th>
        </tr>
        <% @propiedad.parcela.mensuras.each do |mensura| %>
          <tr class="<%= cycle('par','impar') %>">
            <td>
              <%= mensura.mensura_nro %>
            </td>
            <td>
              <%= mensura.mensura_letra %>
            </td>
            <td>
              <%= mensura.iniciador.try(:razon_social).try(:upcase) %>
            </td>
            <td>
              <%= l mensura.fecha_registracion if mensura.fecha_registracion %>
            </td>
          </tr>
        <% end if @propiedad.parcela.mensuras.present? %>         
      </tbody>
    </table>
  </div>
  <div id="resultado"></div>
</fieldset>

app/views/propiedades/new.html.erb
<fieldset class="ui-widget ui-widget-content ui-corner-all" >
<legend class="ui-widget ui-widget-header ui-corner-all">Partida Inmobiliaria</legend>

<%= render 'form', propiedad: @propiedad %>

<%= link_to 'Back', propiedades_path %>
</fieldset>

app/views/propiedades/resultado_busqueda.js.erb
$("#resultado").html('<%=j render partial: "resultado" %>');
$.fancybox.resize();

app/views/propiedades/show.html.erb
<h1><%= @propiedad.partida %></h1>
<fieldset class="ui-widget ui-widget-content ui-corner-all" >  
<legend class="ui-widget ui-widget-header ui-corner-all">Propiedades</legend>
<p id="notice"><%= notice %></p>
<table>
 <tbody>
  <tr>
    <th>Zona:</th>
    <td><%= @propiedad.zona_id %></td>
    <th>Localidad:</th>
    <td><%= @propiedad.localidad.try(:descripcion) if @propiedad.localidad_id %></td>
    <th>Jurisdicción:</th>
    <td><%= @propiedad.jurisdiccion.try(:descripcion) if @propiedad.jurisdiccion_id %></td>
    <th>Fecha Vigencia:</th>
    <td><%= l @propiedad.fecha_vigencia %></td>
  </tr>
</tbody>
</table>
</fieldset>
<fieldset class="ui-widget ui-widget-content ui-corner-all" > 
<legend class="ui-widget ui-widget-header ui-corner-all">R.P.I.</legend>
<table>
<tbody>  
  <tr>
    <th>Tomo:</th>
    <td><%= @propiedad.irp_tomo %></td>
    <th>Folio N°:</th>
    <td><%= @propiedad.irp_folio_real %></td>
    <th>Año:</th>
    <td><%= @propiedad.irp_anio %></td>
    </tr>
</tbody>
</table>
</fieldset>
<fieldset class="ui-widget ui-widget-content ui-corner-all" > 
<legend class="ui-widget ui-widget-header ui-corner-all">Parcela</legend>
<table>
<tbody>  
  <tr>
    <th>Sup. Catastro:</th>
    <td><%= @propiedad.parcela.try(:superficie_catastro) %></td>
    <th>Sup. Mensura</th>
    <td><%= @propiedad.parcela.try(:superficie_mensura) %></td>
  </tr> 
</tbody>
</table>
</fieldset>
<fieldset class="ui-widget ui-widget-content ui-corner-all" > 
<legend class="ui-widget ui-widget-header ui-corner-all">Mensura</legend>
<table>
<tbody>  
  <tr>
    <th>Mensura:</th>
    <td><%= @propiedad.parcela.try(:mensuras).try(:last).try(:mensura_nro) %> - <%= @propiedad.parcela.try(:mensuras).try(:last).try(:mensura_letra) %></td>    
  </tr>
 
</tbody>
</table> 
</fieldset>
<br><br>
<div>
     <%= link_to image_tag("edit"), edit_propiedad_path(@propiedad) %> |
     <%= link_to image_tag("back"), propiedades_path %>
  </div>